### ISSUE TITLE
alliance!

### ISSUE THREAD

**Issue by jlozadad** [ekultails/rootpages#5]
hey noticed this great awesome project! I forked a project before that someone that started doing something similar. Is called linuxjourney. I moved it to gitlab cause I love gitlab.
https://gitlab.com/sysadminonlinux/linuxjourney
Maybe we should merge this stuff ? and avoid re-doing work ?

**Comment by ekultails** [comment]
I love the idea of consolidation!

One of the major concerns I see is that Root Pages is licensed under  the GNU Public License 3 and Linux Journey is using the Creative Commons 4.0. These licenses are incompatible, however, similar material can be ported and used from any source that is referenced.

I also do not know if you are looking for Linux Journey to merge into Root Pages or have Root Pages merge into Linux Journey. If we merge into Root Pages then we have full control over this repository and are not tied to a dead project.

On a somewhat related note, I have been looking into using Sphinx to automatically generate various forms of documentation formats. We can have it all written out into Markdown and then end-users can generate it into PDF, DOCX, HTML, etc. See: https://github.com/ekultails/rootpages/issues/2.

**Comment by jlozadad** [comment]
Probably incorporate all that stuff in to your project. Linuxjourney the original used hugo as a static website. You can probably make it better with what you have.

**Comment by ekultails** [comment]
This would probably be a goal for 2018 to cover all of those topics that are in the Linux Journey in Root Pages. What topics do you find that you reference the most? I can work on creating documentation for that in Root Pages. And pull requests are always welcome!

**Comment by jlozadad** [comment]
I think the main part is how to explain what is linux the history and the distros. Like some of the basic intro on how to certain things.

**Comment by ekultails** [comment]
Thanks for the suggestion! I can work on creating a "operating_systems.md" guide to cover the basics of different Linux distributions. This guide can reference other guides for more details. For example, a "Debian" section could reference "packages.md" on how to use Apt on Debian-based operating systems for installing/updating/removing packages.

**Comment by ekultails** [comment]
I created a new "Operating Systems" document that covers some of the basic differences between most of the major operating systems. How do you feel about the formatting? Would it be better to reformat it as a giant table comparing package managers, descriptions, etc.?

https://github.com/ekultails/rootpages/blob/412dab2c935f63d270a09c1cb71da87b89df8e64/src/operating_systems.rst

I also plan on updating the "Packages" documentation to have more end-user information on how to use package managers. It's currently very developer focused. Alternatively, my "Linux Commands" guide will be refactored and may be a decent way to see how to use package manager commands.

**Comment by ekultails** [comment]
Moved to issue #113
